# Generated by Django 3.1.2 on 2020-10-23 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], max_length=3)),
                ('ammount', models.FloatField()),
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personal_accounting.category', verbose_name='Expense category')),
            ],
        ),
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], max_length=3)),
                ('balance', models.FloatField()),
                ('credit_expenses', models.ManyToManyField(to='personal_accounting.Expense', verbose_name='List of expenses')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=20)),
                ('card_balance', models.FloatField()),
                ('card_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_accounting.bank')),
            ],
        ),
        migrations.CreateModel(
            name='CardExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_accounting.expense')),
                ('expense_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_accounting.card')),
            ],
            bases=('personal_accounting.expense',),
        ),
        migrations.CreateModel(
            name='BankExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_accounting.expense')),
                ('expense_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_accounting.bank')),
            ],
            bases=('personal_accounting.expense',),
        ),
    ]
